# Generated by Django 4.2 on 2023-05-31 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='no_comment',
            field=models.BooleanField(default=False),
        ),
    ]
