# Generated by Django 4.2 on 2023-07-12 08:14

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_user_no_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(default='login/avatar/default_man.png', upload_to='login/avatar'),
        ),
    ]
