# Generated by Django 4.2 on 2023-07-16 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='loved_blog',
            field=models.TextField(blank=True, null=True),
        ),
    ]
