# Generated by Django 4.2 on 2023-07-20 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_user_loved_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='big_detail',
            field=models.TextField(default='<p>这个人很懒，什么都没有写~</p>'),
        ),
        migrations.AddField(
            model_name='user',
            name='small_description',
            field=models.CharField(default='这个人很懒，什么都没有写~', max_length=256),
        ),
    ]
