# Generated by Django 4.2 on 2023-07-12 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_remove_category_c_time_remove_category_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.category', verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='desc',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='摘要'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, to='blog.tag', verbose_name='标签'),
        ),
    ]
