# Generated by Django 4.2 on 2023-07-15 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_blog_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(default='#2655cc', max_length=50, verbose_name='颜色'),
        ),
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(default='#2655cc', max_length=50, verbose_name='颜色'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='seen',
            field=models.IntegerField(default=0, verbose_name='阅读量'),
        ),
    ]
