# Generated by Django 4.2 on 2023-07-15 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_category_color_tag_color_alter_blog_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='comment_num',
            field=models.IntegerField(default=0, verbose_name='评论数'),
        ),
    ]
