# Generated by Django 4.2 on 2023-07-15 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_blog_comment_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='love',
            field=models.IntegerField(default=0, verbose_name='点赞数'),
        ),
    ]
