# Generated by Django 4.2 on 2023-07-16 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_comment_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='comment_num',
        ),
    ]
