# Generated by Django 4.2 on 2023-07-16 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_remove_blog_comment_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='status',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='status',
        ),
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, '正常'), (2, '草稿')], default=1, verbose_name='状态'),
        ),
    ]
