# Generated by Django 4.2 on 2023-07-21 04:02

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_remove_category_status_remove_tag_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='cover',
            field=imagekit.models.fields.ProcessedImageField(default='blog/cover/default_cover.png', upload_to='blog/cover'),
        ),
    ]
