# Generated by Django 4.2 on 2023-07-21 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_blog_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='comment_num',
            field=models.IntegerField(default=0, verbose_name='评论数'),
        ),
    ]
